name: Rust CI

on:
  push:
    branches: [ "main", "master", "feature/*" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  CARGO_TERM_COLOR: always
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    name: Build and Check
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt
    
    - name: Rustfmt Check
      run: cargo fmt --all -- --check
      continue-on-error: true
      
    - name: Cargo Clippy
      run: cargo clippy -- -D warnings
      continue-on-error: true
      
    - name: Build Project (Release)
      run: cargo build --release --verbose

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: win-remote-touch-windows
        path: target/release/win-remote-touch.exe
        retention-days: 7
